apiVersion: v1
kind: Service
metadata:
  name: jaeger-elasticsearch
  labels:
    app: jaeger-elasticsearch
spec:
  selector:
    app: jaeger-elasticsearch
  ports:
    - port: 9200
      targetPort: 9200