apiVersion: v1
kind: Service
metadata:
  name: jaeger-elasticsearch
  labels:
    app: jaeger-elasticsearch
spec:
  selector:
    app: jaeger-elasticsearch
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300
